#ifndef Abstractor_h
#define Abstractor_h

#include <iostream>
#include <string>
#include <stdlib.h>     /* srand, rand */
#include <time.h>  /* time */
#include <map>
#include <list>
#include <algorithm>

#include "NodeSystem.h"
#include "Connector.h"


using namespace std;

class Abstractor
{
public:

	map<int, int> frequency_table;
	map<int, int> accepted_frequency;
	map<int, list<int>> inputs;

	//Changes generated by addition or removeal of random nodes 
	map<int, list<int>> modifications;
	//Child connection nodes of Parent
	list<int> changes;
	//tracks the response after each modification
	map<int, int> feedback;

	list<int> dataset;
	
	NodeSystem *node_system;
	Connector *connections;

	int size = 0;

	Abstractor();

	Abstractor(NodeSystem *pNodeSystem);

	void Input(int ascChar);

	void GetFeedback();

	void GenerateRandomDataSet(int max_size = 0);

	void GenerateRandomNodes(int max_size = 0);

	void GenerateRandomConnections(int max_size = 0);

	void OutputFrequencyTable();

	void SeparateByFrequency(int frequency_count);

	void Output();

	void LogInputs();

	void OutputInputs();

	bool IsChanged();

	/*   
	*Abstraction of trial and error method
	*Create a new node.
	*Create random connections.
	*Get Feedback on correctness of sugesstion(guess).
	*modify guess by add or remove nodes.
	*Get feedback on nodes
	*retry until solution is reached.
	*/

	Node *test_node = NULL;
	//use to compare modification
	//with previous modifications
	list<int> current_modification;

	//Node creation process
	Node* CreateNode();
	void CreateRandomNodeConnection(Node *pNode);

	void CreateRandomNodeConnections(Node *pNode, int max_size = 0);
	

	//Feedback and update
	int GetFeedBack();

	void ModifyTestNode(int hint = 0, int affinity = 0, int connection_id = 0);

	void LogChanges(int responses, int affinity);

	void OutputModifications();

	void OutputFeedback();

	int AnalizeModification(int modification_id);

	int CompareFeedBack(int feedback);

	int GenerateHint(int feedback);

	void Run();


private:
	void GenerateFrequencyTable();
};

#endif